### ISSUE TITLE
mass_worker.py: TypeError: expected string or buffer

### ISSUE THREAD

**Issue by nemobis** [rohit-dua/BUB#46]
I think this killed a worker:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/project/bub/public_html/BUB/bot/mass_worker.py", line 392, in wait_and_add_to_queue
    info = json.loads(q_bulk_order.pop_and_remove())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

I guess enclose everything in a `try` and return proper status?

**Comment by nemobis** [comment]
Not the first time I get a crash right after the start of a new mass worker:

```
2016-01-21 21:25:04.397647  Started Mass Worker #1
2016-01-21 21:25:04.400248  Started wait_and_add_to_queue
2016-01-21 21:25:05.153668  func:manager  args:(<__main__.QueueHandler object at 0x2b4a5b16a2d0>,){}
  :<type 'exceptions.IndexError'>, Retry in 1 seconds...
2016-01-21 21:27:01.710761  Started Mass Worker #3
2016-01-21 21:56:52.652950  sSYcZtlK2bkC  Not Public Domain
2016-01-21 22:01:42.678483  sSemVtZnVE0C  Not Public Domain
  :<type 'exceptions.IndexError'>, Retry in 2 seconds...Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/project/bub/public_html/BUB/bot/mass_worker.py", line 392, in wait_and_add_to_queue
    info = json.loads(q_bulk_order.pop_and_remove())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
