### ISSUE TITLE
503

### ISSUE THREAD

**Issue by bodhisattwawiki** [rohit-dua/BUB#52]
Bub is down for quite a long time. It shows No webservice.

**Comment by rohit-dua** [comment]
I got this when running `webservice start`

```
Traceback (most recent call last):
  File "/usr/local/bin/webservice", line 7, in <module>
    from toollabs.webservice.backends import Backend, GridEngineBackend, KubernetesBackend
  File "/usr/lib/python2.7/dist-packages/toollabs/webservice/backends/__init__.py", line 3, in <module>
    from toollabs.webservice.backends.kubernetesbackend import KubernetesBackend
  File "/usr/lib/python2.7/dist-packages/toollabs/webservice/backends/kubernetesbackend.py", line 3, in <module>
    import pykube
  File "/usr/lib/python2.7/dist-packages/pykube/__init__.py", line 8, in <module>
    from .objects import (  # noqa
  File "/usr/lib/python2.7/dist-packages/pykube/objects.py", line 16, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

Not sure if its labs error or BUB.

**Comment by ricordisamoa** [comment]
The `python_2_unicode_compatible` decorator has been added in six 1.9.0: https://bitbucket.org/gutworth/six/src/ca4580a5a648fc75abc568907e81abc80b05d58c/CHANGES?fileviewer=file-view-default#CHANGES-34

**Comment by bodhisattwawiki** [comment]
Again its 503

**Comment by ricordisamoa** [comment]
See also https://phabricator.wikimedia.org/T144554
